# Generated by Django 2.2.20 on 2021-08-11 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210811_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='imageFile',
            new_name='image',
        ),
    ]
